# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='riddles',
        ),
        migrations.AddField(
            model_name='riddle',
            name='categories',
            field=models.ManyToManyField(to='riddles.Category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='register_image',
            field=models.ImageField(blank=True, null=True, upload_to='register_images', verbose_name='pic/register image'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic/logos', verbose_name='logo image'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='min_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic/min_logos', verbose_name='min image'),
        ),
    ]
