# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20160908_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='times_resolved',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
