# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_auto_20160908_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='rate',
        ),
    ]
