# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_remove_riddle_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
