# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0006_auto_20160914_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='register_image',
            field=models.ImageField(blank=True, null=True, upload_to='register_images', verbose_name='register image'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logo image'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='min_image',
            field=models.ImageField(blank=True, null=True, upload_to='min_logos', verbose_name='min image'),
        ),
    ]
