# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riddles', '0006_auto_20160914_1901'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
                ('expirience', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('solved_riddles', models.ManyToManyField(to='riddles.Riddle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
