# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161015_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='profile pic'),
        ),
    ]
