# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='experience',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
