# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-26 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170126_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lvl',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
